//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kullaniciProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int Id { get; set; }
        public string K_Ad { get; set; }
        public string Ad_Soyad { get; set; }
        public string Sifre { get; set; }
        public string Grup { get; set; }
        public string K_Tur { get; set; }
    }
}
